### ISSUE TITLE
AWS开香港区了，珠三角地区连香港比东京快无数倍

### ISSUE THREAD

**Issue by buhiroshi0205** [haohanshi/Freshman-Prepare-Guide#2]
https://github.com/haohanshi/Freshman-Prepare-Guide/blob/260d3367e6a0e9c5556d658d86afdb343a744da8/guide/templates/guide/vpn.html#L95

**Comment by haohanshi** [comment]
> https://github.com/haohanshi/Freshman-Prepare-Guide/blob/260d3367e6a0e9c5556d658d86afdb343a744da8/guide/templates/guide/vpn.html#L95

刚刚测试了一下，可能因为网络拥堵的原因香港的非常非常慢，开谷歌都要等很久，而且香港的ip段太少了，只有18.162.0.0/16和18.163.0.0/16。现在比较稳定的还是新加坡和首尔
55f8a38

**Comment by buhiroshi0205** [comment]
好吧，反正我从东莞用着香港很爽，其次东京。新加坡较慢，首尔没用过
